language: ruby

rvm:
  - 2.4

before_script:
  - gem install awesome_bot

script:
  - awesome_bot README.md --allow-redirect --allow-ssl --white-list https://www.openbsd.org/mail.html

notifications:
  email:
    recipients:
      - estetus+travis-ci@gmail.com
    on_success: change
    on_failure: always
